<option value="">Escolha uma Opção</option>
<option value="Engenheiro Mecânico">Engenheiro Mecânico</option>
<option value="Engenheiro Elétrico">Engenheiro Elétrico</option>
<option value="Engenheiro Civil">Engenheiro Civil</option>
<option value="Engenheiro Automação">Engenheiro Automação</option>
<option value="Analista de Manutenção">Analista de Manutenção</option>
<option value="Analista de Projetos">Analista de Projetos</option>
<option value="Analista de Sistemas">Analista de Sistemas</option>
<option value="Coordenador de Manutenção">Coordenador de Manutenção</option>
<option value="Gerente de Manutenção">Gerente de Manutenção</option>
<option value="Planejador de Manutenção">Planejador de Manutenção</option>
<option value="Programador de Manutenção">Programador de Manutenção</option>
<option value="Técnico em Refrigeração">Técnico em Refrigeração</option>
<option value="Técnico em Mecânica">Técnico em Mecânica</option>
<option value="Técnico em Eletrotécnica">Técnico em Eletrotécnica</option>
<option value="Técnico em Automação">Técnico em Automação</option>
<option value="Arquiteto">Arquiteto</option>
<option value="Atífice de Manutenção">Atífice de Manutenção</option>
<option value="Supervisor de Manutenção">Supervisor de Manutenção</option>
<option value="Supervisor de Limpeza">Supervisor de Limpeza</option>
<option value="Supervisor de Jardinagem">Supervisor de Jardinagem</option>
<option value="Jardineiro">Jardineiro</option>
<option value="Pedreiro">Pedreiro</option>
<option value="Servente">Servente</option>
<option value="Mestre de obras">Mestre de obras</option>
<option value="Auxiliar de elétrica">Auxiliar de elétrica</option>
<option value="Auxiliar de mecânica">Auxiliar de mecânica</option>
<option value="Auxiliar de automação">Auxiliar de automação</option>
<option value="Auxiliar de refrigeração">Auxiliar de refrigeração</option>
<option value="Desenvolvedor de sistemas">Desenvolvedor de sistemas</option>
<option value="Copeiro">Copeiro</option>
<option value="Pintor">Pintor</option>
<option value="Eng. de Segurança do Trabalho">Eng. de Segurança do Trabalho</option>
<option value="Técnico em Segurança do Trabalho">Técnico em Segurança do Trabalho</option>
<option value="Comprador">Comprador</option>
<option value="Assistente administrativo">Assistente administrativo</option>
<option value="Técnico em Edificações">Técnico em Edificações</option>
<option value="Analista de TI">Analista de TI</option>
<option value="Técnico de TI">Técnico de TI</option>
<option value="Engenheiro de Software">Engenheiro de Software</option>
<option value="Engenheiro de TI">Engenheiro de TI</option>
<option value="Bombeiro hidráulico">Bombeiro hidráulico</option>
<option value="Designer Gráfico">Designer Gráfico</option>
<option value="Auxiliar administrativo">Auxiliar administrativo</option>
<option value="Auxiliar de limpeza">Auxiliar de limpeza</option>
<option value="Engenheiro de Manutenção">Engenheiro de Manutenção</option>
<option value="Engenheiro de Projetos">Engenheiro de Projetos</option>
<option value="Engenheiro de Planejamento">Engenheiro de Planejamento</option>
<option value="Analista de Meio Ambiente">Analista de Meio Ambiente</option>
<option value="Técnico de Meio Ambiente">Técnico de Meio Ambiente</option>
<option value="Engenheiro de Meio Ambiente">Engenheiro de Meio Ambiente</option>
<option value="Técnico em CFTV">Técnico em CFTV</option>
<option value="Outros">Outros</option>
<option value="Copeiro">Copeiro</option>
